package note

import (
	"strings"
	"testing"
	"time"

	"schoolwork-check/internal/model"
)

func ptr[T any](v T) *T { return &v }

func sampleTask() model.Task {
	due := time.Date(2026, 9, 19, 23, 59, 0, 0, time.UTC)
	sub := time.Date(2026, 9, 18, 10, 0, 0, 0, time.UTC)
	return model.Task{
		ID: "canvas:assignment:501", Source: model.SourceCanvas, Kind: model.KindAssignment,
		Course: "AP Calculus", Title: "Problem Set 4", URL: "https://c/501",
		DueAt: &due, Points: ptr(20.0),
		Description: "Complete problems 1-12.\n- Show work",
		Attachments: []model.Attachment{{Name: "handout.pdf", URL: "https://c/f/9", Content: "Differentiate x^2"}},
		Progress: model.Progress{State: model.StateSubmitted, SubmittedAt: &sub, Grade: "18/20",
			Text: "my answers", Attachments: []model.Attachment{{Name: "ps4.pdf", URL: "https://c/f/10", Content: "1. 2x"}}},
	}
}

func TestRender(t *testing.T) {
	r := Render(sampleTask(), RenderOptions{CoursePrefix: true})

	if r.Title != "AP Calculus — Problem Set 4" {
		t.Errorf("title = %q", r.Title)
	}
	if r.State != "done" || r.ExternalID != "canvas:assignment:501" || r.URL != "https://c/501" {
		t.Errorf("state/id/url = %q %q %q", r.State, r.ExternalID, r.URL)
	}
	for _, want := range []string{"Due: Sat Sep 19 23:59\n", "Course: AP Calculus", "Kind: assignment · 20 pts", "Link: https://c/501", "Complete problems 1-12.\n- Show work", "Attachments:\n- handout.pdf (https://c/f/9)"} {
		if !strings.Contains(r.Description, want) {
			t.Errorf("description missing %q:\n%s", want, r.Description)
		}
	}
	for _, want := range []string{"Progress: submitted, grade 18/20, submitted Fri Sep 18 10:00", "Submitted text:\nmy answers", "Submitted files:\n- ps4.pdf (https://c/f/10)", "--- Your file: ps4.pdf ---\n1. 2x", "--- Handout: handout.pdf ---\nDifferentiate x^2"} {
		if !strings.Contains(r.Notes, want) {
			t.Errorf("notes missing %q:\n%s", want, r.Notes)
		}
	}
	if !strings.HasSuffix(r.Notes, "\n"+Sentinel+"canvas:assignment:501") {
		t.Errorf("notes must end with sentinel:\n%s", r.Notes)
	}
	// Student work comes before handouts.
	if strings.Index(r.Notes, "Your file") > strings.Index(r.Notes, "Handout") {
		t.Error("student work should precede handouts")
	}
}

func TestRenderMinimal(t *testing.T) {
	r := Render(model.Task{ID: "x:1", Kind: model.KindMaterial, Title: "  "}, RenderOptions{})
	if r.Title != "(untitled)" || r.State != "open" {
		t.Errorf("got %q %q", r.Title, r.State)
	}
	if !strings.HasPrefix(r.Description, "Due: none\nKind: material") {
		t.Errorf("description:\n%s", r.Description)
	}
	if r.Notes != "Progress: \n"+Sentinel+"x:1" && !strings.HasSuffix(r.Notes, Sentinel+"x:1") {
		t.Errorf("notes:\n%s", r.Notes)
	}
}

func TestMapState(t *testing.T) {
	cases := map[model.State]string{
		model.StateNotStarted: "open", model.StateMissing: "open", model.StateInProgress: "in_progress",
		model.StateSubmitted: "done", model.StateGraded: "done", model.StateExcused: "done", model.State("weird"): "open",
	}
	for in, want := range cases {
		if got := MapState(in); got != want {
			t.Errorf("MapState(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestTruncationKeepsSentinelAndLimits(t *testing.T) {
	task := sampleTask()
	task.Description = strings.Repeat("é", 20000)
	task.Attachments[0].Content = strings.Repeat("λ", 20000)
	task.Progress.Attachments[0].Content = strings.Repeat("λ", 20000)
	r := Render(task, RenderOptions{})
	if len(r.Description) > maxTextBytes || len(r.Notes) > maxTextBytes {
		t.Errorf("over limits: desc=%d notes=%d", len(r.Description), len(r.Notes))
	}
	if !strings.HasSuffix(r.Notes, Sentinel+task.ID) {
		t.Error("sentinel lost after truncation")
	}
	for _, s := range []string{r.Description, r.Notes, r.Title} {
		if !isValidUTF8(s) {
			t.Error("truncation split a rune")
		}
	}
}

func isValidUTF8(s string) bool {
	for _, r := range s {
		if r == '\uFFFD' {
			return false
		}
	}
	return true
}

func TestRenderEnrichment(t *testing.T) {
	task := sampleTask()
	task.Enrichment = &model.Enrichment{
		Summary: "Differentiate twelve polynomials.", Deliverable: "PDF upload",
		Steps: []string{"Do 1-6", "Do 7-12"}, Requirements: []string{"Show work"},
		EstimateMin: ptr(90), Model: "deepseek/deepseek-v4-flash",
	}
	r := Render(task, RenderOptions{})
	for _, want := range []string{
		"Estimate: ~1.5 h\nLink:",
		"\nDifferentiate twelve polynomials.\nHand in: PDF upload\n",
		"Steps:\n1. Do 1-6\n2. Do 7-12\n",
		"Requirements:\n- Show work\n",
		"(brief generated by deepseek/deepseek-v4-flash)\n\nFrom the teacher:\nComplete problems 1-12.",
	} {
		if !strings.Contains(r.Description, want) {
			t.Errorf("description missing %q:\n%s", want, r.Description)
		}
	}
	if strings.Contains(Render(sampleTask(), RenderOptions{}).Description, "From the teacher") {
		t.Error("label should only appear with a brief")
	}
}

func TestFormatMinutes(t *testing.T) {
	for m, want := range map[int]string{45: "45 min", 60: "1 h", 90: "1.5 h", 240: "4 h"} {
		if got := FormatMinutes(m); got != want {
			t.Errorf("FormatMinutes(%d) = %q, want %q", m, got, want)
		}
	}
}

// TestRenderIsStableOverTime guards against churn: nothing in the rendering
// may depend on the clock, or every run would PATCH every dated task.
func TestRenderIsStableOverTime(t *testing.T) {
	task := sampleTask()
	for _, agent := range []bool{false, true} {
		o := RenderOptions{CoursePrefix: true, Location: time.UTC, AgentOwnsDescription: agent}
		a := Render(task, o)
		time.Sleep(2 * time.Millisecond)
		b := Render(task, o)
		if a != b {
			t.Errorf("agent=%v: rendering changed between two calls", agent)
		}
	}
}

func TestRenderTitleIsOneLine(t *testing.T) {
	task := sampleTask()
	task.Course = "  7 Greksouk\tAP Latin "
	task.Title = "tentative schedule: \n6.1-12 quiz: Sept 10\r\n6.13-end quiz: tbd"
	r := Render(task, RenderOptions{CoursePrefix: true})
	if want := "7 Greksouk AP Latin — tentative schedule: 6.1-12 quiz: Sept 10 6.13-end quiz: tbd"; r.Title != want {
		t.Errorf("title = %q, want %q", r.Title, want)
	}
}
